---
# Webdev

- name: Minimal
  hosts: all
  remote_user: vagrant
  become: true
  roles:
    - Essential
    - NPM
    - webpack
    - bower


- name: HTTP
  hosts: WebDev
  remote_user: vagrant
  become: true
  roles:
    - Essential
    - PHP7
    - Apache2
    - MariaDB
    - PostGreSQL
    - Git

