---
- name: Install Vim
  apt:
      name: vim
      state: latest

- name: Install wget
  apt:
      name: wget
      state: latest

- name: Install git
  apt:
      name: git
      state: latest

- name: apt-upgrade
  apt:
      upgrade: dist

