---
- name: apt-update
  apt:
      update_cache: 'yes'

- name: apt-upgrade
  apt:
      upgrade: dist

- name: Install Vim
  apt:
      name: vim
      state: latest

- name: Install wget
  become: true
  apt:
      name: wget
      state: latest

- name: Install git
  become: true
  apt:
      name: git
      state: latest

