---
- name: Add repo for PHP7
  apt_repository: repo="deb http://packages.dotdeb.org {{ ansible_distribution_release }} all" state=present
- name: Add apt key for Debian
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg state=present
- name: apt-update
  apt:
      update_cache: 'yes'

- name: apt-upgrade
  apt:
      upgrade: dist

- name: Install PHP7
  become: true
  apt:
      name: libapache2-mod-php7.0
      state: latest

