---
# LAMP

- name: HTTP
  hosts: web
  remote_user: vagrant
  become: true
  roles:
    - Essential
    - PHP7
    - Apache2


- name: BDD
  hosts: bdd
  remote_user: vagrant
  become: true
  roles:
    - Essential
    - MariaDB

